using SharedKernel.Contracts;

namespace Installer.Core.SiteConfig;

/// <summary>
/// Loads and validates the site configuration pack (<c>.epcfg</c>) that identifies a PACS node.
///
/// The pack carries <b>site identity and site facts</b> — which PACS this is, where its data
/// lives, which ports, which backup targets. It deliberately does not carry <i>state policy</i>:
/// in the L2-R2 estate that lives in <c>appsettings.&lt;STATE&gt;.json</c>, generated by
/// <c>build/generate-state-config.py</c> and governed by the state-variation doctrine. A pack
/// that could override state policy would route around that doctrine, so this loader reads
/// identity and refuses to be a second policy channel.
/// </summary>
public interface ISiteConfigLoader
{
    /// <summary>
    /// Reads, parses and validates a <c>.epcfg</c> file.
    /// </summary>
    /// <param name="path">Path to the pack.</param>
    /// <param name="allowUnsigned">
    /// When false (the default, and what an installation must use), a pack with no usable
    /// signature is rejected. Set only for development against an unsigned pack.
    /// </param>
    Task<SiteConfigPack> LoadAsync(string path, bool allowUnsigned = false, CancellationToken cancellationToken = default);
}

/// <summary>
/// Raised when a site configuration pack is missing, unparseable, incomplete or unsigned.
///
/// Always fatal. A half-read pack means the installer proceeds with some site values defaulted:
/// the node installs "successfully" under the wrong PacsId, or writes its data somewhere the
/// backup schedule does not cover, and nothing says so until someone goes looking months later.
/// </summary>
public sealed class SiteConfigException : Exception
{
    public SiteConfigException(string message) : base(message) { }
    public SiteConfigException(string message, Exception inner) : base(message, inner) { }
    public SiteConfigException() { }
}
