using System.Globalization;
using System.Text;
using SharedKernel.Contracts;

namespace Installer.Actions.Install;

/// <summary>
/// Renders a <c>ServiceMapEntry</c> as a systemd unit.
///
/// Pure — options and an entry in, text out. No filesystem, no process, no clock. A unit file is
/// exactly the kind of artefact that is written once, never read again, and subtly wrong for two
/// years, so every property that matters below has a test asserting it is present.
///
/// ── CONSISTENCY WITH THE ESTATE, WHICH IS THE POINT ─────────────────────────────────────────
///
/// `ops/ansible/roles/deployapp/templates/l2r2-service.service.j2` already generates units for
/// all 26 services on the online estate, and it is not naive. It carries the tier ordering, the
/// ASPNETCORE_ENVIRONMENT state selection, a restart policy with a burst limit, LimitNOFILE
/// sized against the connection-pool arithmetic, and a deliberately modest hardening profile.
///
/// This writer reproduces that shape. Two different unit shapes for the same services — one from
/// Ansible online, one from the installer offline — is how an offline node comes to behave
/// differently from the estate under load, in a way nobody can see until it does. ADR-0010
/// records this as the single largest risk of having two authorities, and the long-term fix is
/// one generated topology feeding both.
/// </summary>
public static class SystemdUnitWriter
{
    /// <summary>Unit file name for a service, e.g. <c>epacs-ePACSWeb.service</c>.</summary>
    public static string UnitFileName(ServiceMapEntry service) => $"{UnitName(service)}.service";

    /// <summary>
    /// Unit name. Prefixed so every unit this installer owns is identifiable at a glance and by
    /// glob — <c>systemctl status 'epacs-*'</c> — and so it can never collide with a unit the
    /// distribution or the estate's own Ansible put there.
    /// </summary>
    public static string UnitName(ServiceMapEntry service) => $"epacs-{service.Name}";

    public static string Render(ServiceMapEntry service, string runUser, Func<string, string> resolveTokens)
    {
        ArgumentNullException.ThrowIfNull(service);
        ArgumentNullException.ThrowIfNull(resolveTokens);
        ArgumentException.ThrowIfNullOrWhiteSpace(runUser);

        var exec = resolveTokens(service.Executable);
        var args = string.IsNullOrWhiteSpace(service.Arguments) ? "" : " " + resolveTokens(service.Arguments);
        var c = CultureInfo.InvariantCulture;
        var sb = new StringBuilder();

        sb.AppendLine(c, $"# {UnitName(service)} — GENERATED BY THE ePACS INSTALLER. DO NOT EDIT ON THE HOST.");
        sb.AppendLine("# Hand edits are lost on the next repair or upgrade and, worse, make two nodes differ in a");
        sb.AppendLine("# way nobody can see. Change the service map instead.");
        sb.AppendLine();

        sb.AppendLine("[Unit]");
        sb.AppendLine(c, $"Description={service.DisplayName}");
        if (service.Description is not null)
        {
            sb.AppendLine(c, $"Documentation=text:{service.Description}");
        }
        sb.AppendLine("After=network-online.target");
        sb.AppendLine("Wants=network-online.target");
        sb.AppendLine();

        sb.AppendLine("[Service]");
        sb.AppendLine("Type=simple");
        sb.AppendLine(c, $"User={runUser}");
        sb.AppendLine(c, $"Group={runUser}");
        sb.AppendLine(c, $"ExecStart={exec}{args}");
        sb.AppendLine();

        if (service.Environment.Count > 0)
        {
            sb.AppendLine("# ONE CODEBASE, MANY STATES. ASPNETCORE_ENVIRONMENT selects");
            sb.AppendLine("# appsettings.<STATE>.json inside the service. Getting it wrong does not fail — it runs");
            sb.AppendLine("# the wrong state's configuration, silently, which is far worse.");
            foreach (var (key, value) in service.Environment.OrderBy(kv => kv.Key, StringComparer.Ordinal))
            {
                sb.AppendLine(c, $"Environment={key}={resolveTokens(value)}");
            }
            sb.AppendLine();
        }

        sb.AppendLine("# Restart on failure, but not in a tight loop. A service that cannot reach the database");
        sb.AppendLine("# fails fast and repeatedly; a backoff with a burst limit keeps the journal readable and");
        sb.AppendLine("# stops a dependency outage from becoming a CPU incident.");
        sb.AppendLine(c, $"Restart={RestartPolicy(service)}");
        sb.AppendLine(c, $"RestartSec={Math.Max(1, service.Recovery.FirstFailure.DelaySeconds)}");
        sb.AppendLine("StartLimitBurst=5");
        sb.AppendLine(c, $"StartLimitIntervalSec={service.Recovery.ResetAfterSeconds}");
        sb.AppendLine();

        sb.AppendLine("StandardOutput=journal");
        sb.AppendLine("StandardError=journal");
        sb.AppendLine(c, $"SyslogIdentifier={UnitName(service)}");
        sb.AppendLine();

        sb.AppendLine("# Hardening, modest on purpose: these services legitimately write report files and logs,");
        sb.AppendLine("# so ProtectSystem=strict would break them in ways that look like application bugs.");
        sb.AppendLine("NoNewPrivileges=true");
        sb.AppendLine("PrivateTmp=true");
        sb.AppendLine("ProtectSystem=full");
        sb.AppendLine("ProtectHome=true");
        if (service.DataDirectories.Length > 0)
        {
            sb.AppendLine(c, $"ReadWritePaths={string.Join(' ', service.DataDirectories.Select(resolveTokens))}");
        }
        sb.AppendLine();

        sb.AppendLine("# 26 services each pooling up to 2000 database connections, plus HTTP sockets, exhaust the");
        sb.AppendLine("# default 1024 long before the pool limit is reached — and the symptom is");
        sb.AppendLine("# \"Too many open files\", which reads as a code leak.");
        sb.AppendLine("LimitNOFILE=65535");
        sb.AppendLine();

        sb.AppendLine("[Install]");
        sb.AppendLine("WantedBy=multi-user.target");

        return sb.ToString();
    }

    /// <summary>
    /// Maps the service map's recovery action onto a systemd restart policy.
    ///
    /// <c>restart_and_bundle</c> has no systemd equivalent — collecting a support bundle after
    /// repeated failure is the Installer Agent's job, not the service manager's — so it maps to
    /// <c>on-failure</c> and the bundling stays where it already lives.
    /// </summary>
    private static string RestartPolicy(ServiceMapEntry service) =>
        service.Recovery.FirstFailure.Action.ToLowerInvariant() switch
        {
            "none" => "no",
            _ => "on-failure"
        };
}
