using System.Globalization;
using System.Text;
using SharedKernel.Configuration;

namespace Installer.Actions.Database;

/// <summary>
/// Generates the MySQL server configuration for a PACS node.
///
/// Pure: it takes options and a verdict, and returns text. No file system, no process, no
/// clock — so every value below is testable, and the ones that matter have tests asserting they
/// are present. A configuration file is exactly the kind of artefact that is written once,
/// never reviewed, and wrong for two years.
/// </summary>
public static class MyIniWriter
{
    /// <summary>
    /// Renders <c>my.ini</c>.
    /// </summary>
    /// <param name="options">Server options (ports, paths, sizing).</param>
    /// <param name="dataRoot">Resolved data root; <c>${DataRoot}</c> tokens expand against it.</param>
    /// <param name="verdict">
    /// The file system's case-sensitivity verdict. Decides <c>lower_case_table_names</c>, which
    /// is fixed at initialisation and can never be changed afterwards.
    /// </param>
    public static string Render(MySqlServiceOptions options, string dataRoot, CaseSensitivityVerdict verdict)
    {
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(verdict);
        ArgumentException.ThrowIfNullOrWhiteSpace(dataRoot);

        var dataDir = Expand(options.DataDir, dataRoot);
        var logDir = Expand(options.LogDir, dataRoot);
        var durability = options.StrictDurability ? 1 : 0;
        var c = CultureInfo.InvariantCulture;

        var sb = new StringBuilder();
        sb.AppendLine("# ePACS MySQL configuration — GENERATED BY THE INSTALLER. DO NOT EDIT ON THE HOST.");
        sb.AppendLine("# Hand edits are lost on the next repair or upgrade and, worse, make two PACS nodes");
        sb.AppendLine("# differ in a way nobody can see. Change the installer's configuration instead.");
        sb.AppendLine();
        sb.AppendLine("[mysqld]");
        sb.AppendLine(c, $"port = {options.Port}");
        sb.AppendLine(c, $"datadir = {dataDir}");
        sb.AppendLine(c, $"log-error = {Path.Combine(logDir, "mysql-error.log")}");
        sb.AppendLine();

        sb.AppendLine("# ── Table name case ─────────────────────────────────────────────────────────");
        sb.AppendLine("# FIXED AT INITIALISATION. It cannot be changed on a populated server, which is");
        sb.AppendLine("# why the installer refuses rather than repairs when it cannot be set to 0.");
        sb.AppendLine(c, $"# {verdict.Explanation}");
        sb.AppendLine(c, $"lower_case_table_names = {verdict.RequiredLowerCaseTableNames}");
        sb.AppendLine();

        sb.AppendLine("# ── Character set ───────────────────────────────────────────────────────────");
        sb.AppendLine("# utf8mb4 and the 0900 collation, matching ops/compose and every state database.");
        sb.AppendLine("# A node that stored Devanagari or Telugu member names under a different collation");
        sb.AppendLine("# would sort and compare them differently from the state's own copy.");
        sb.AppendLine("character-set-server = utf8mb4");
        sb.AppendLine("collation-server = utf8mb4_0900_ai_ci");
        sb.AppendLine();

        sb.AppendLine("# ── Durability ──────────────────────────────────────────────────────────────");
        sb.AppendLine("# A PACS node loses power. That is the premise of this product, not an edge case.");
        sb.AppendLine("# These two settings mean a committed voucher is on the platter before the caller");
        sb.AppendLine("# is told it committed. They cost throughput; the books are worth more.");
        sb.AppendLine(c, $"innodb_flush_log_at_trx_commit = {durability}");
        sb.AppendLine(c, $"sync_binlog = {durability}");
        sb.AppendLine("innodb_doublewrite = ON");
        sb.AppendLine();

        sb.AppendLine("# ── Connections ─────────────────────────────────────────────────────────────");
        sb.AppendLine("# See ops/ansible/group_vars/all.yml: the ERP services ship Max Pool Size=2000 each.");
        sb.AppendLine("# MySQL's own default of 151 is met for the first time during a state cutover, and");
        sb.AppendLine("# 'Too many connections' reads as a database outage rather than as pool sizing.");
        sb.AppendLine(c, $"max_connections = {options.MaxConnections}");
        sb.AppendLine();

        sb.AppendLine("# ── Memory ──────────────────────────────────────────────────────────────────");
        sb.AppendLine(c, $"innodb_buffer_pool_size = {options.InnodbBufferPoolBytes}");
        sb.AppendLine();

        sb.AppendLine("# ── Network exposure ────────────────────────────────────────────────────────");
        sb.AppendLine("# Localhost only. Nothing outside this machine may reach the database directly:");
        sb.AppendLine("# the node holds a society's books and sits on a network nobody administers.");
        sb.AppendLine("bind-address = 127.0.0.1");
        sb.AppendLine("skip-name-resolve = ON");
        sb.AppendLine();

        sb.AppendLine("[client]");
        sb.AppendLine(c, $"port = {options.Port}");
        sb.AppendLine("default-character-set = utf8mb4");

        return sb.ToString();
    }

    /// <summary>
    /// Expands <c>${DataRoot}</c>. Separators are deliberately NOT normalised here: this text
    /// is read by mysqld on the target machine, not by this process, so it must carry the
    /// target's separators rather than the build agent's.
    /// </summary>
    private static string Expand(string value, string dataRoot) =>
        value.Replace("${DataRoot}", dataRoot.TrimEnd('/', '\\'), StringComparison.OrdinalIgnoreCase);
}
