<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- No application entry point; pure library. -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="MySqlConnector" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Polly.Extensions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Confluent.Kafka" />
  </ItemGroup>

</Project>
